### ISSUE TITLE
Sites does not support different datatypes (Long and Float)

### ISSUE THREAD

**Issue by gursimar** [uber/pyro#1574] opened 2018-11-28 02:13 UTC
### Issue Description
Sites does not support both float and long tensor types. I introduced another categorical variable in the weather example, and put that in the sites for the importance sampling but it throws a type error saying that a float tensor was expected. I saw pytorch's documentation that they return a Long tensor when sampling from a Bernoulli and a FloatTensor when sampling from a Categorical. Shouldn't sites support different datatypes anyways?

### Environment
 - Ubuntu 16.04 and python 3.6.5
- Pytorch version 0.4.1
- Pyro version 0.2.1

### Code Snippet
```
def weather():
    cloudy = pyro.sample('cloudy', dist.Bernoulli(0.3))
    cloudy = 'cloudy' if cloudy.item() == 1.0 else 'sunny'
    mean_temp = {'cloudy': 55.0, 'sunny': 75.0}[cloudy]
    scale_temp = {'cloudy': 10.0, 'sunny': 15.0}[cloudy]
    temp = pyro.sample('temp', dist.Normal(mean_temp, scale_temp))
    NEW_CAT_VAR = pyro.sample("aux_var", dist.Categorical(torch.ones(5)))
    return cloudy, temp.item()

posterior = pyro.infer.Importance(weather, num_samples = 100)
marginal = pyro.infer.EmpiricalMarginal(posterior.run(), sites=["temp", "cloudy"])
print(marginal()) # this works
marginal = pyro.infer.EmpiricalMarginal(posterior.run(), sites=["temp", "cloudy", "aux_var"])
print(marginal()) # this does not work
```

**Comment by eb8680** [comment] 2018-11-28 02:45
Thanks for pointing this out.  To be clear, the issue is that `pyro.infer.EmpiricalMarginal` does not support computing the joint marginal distribution of sites with different types, because it tries to `torch.stack` values at each site in a single sample from the joint distribution.

As of #1524 we've removed most uses of `EmpiricalMarginal` from the tutorials and examples except in `HMC`, where this issue wouldn't come up because all random variables must be continuous when using HMC.  It's therefore unlikely that we'll add support for this ourselves, because there aren't many use cases for it.  Worth keeping in mind for #1226 or future PRs updating `pyro.distributions.Empirical`, though.

**Comment by gursimar** [comment] 2018-11-28 04:21
Thanks for making it clear. I agree with you that marginal of the joint might not be an important use case but this issue also appears while computing multivariate posterior (with different types) which is an important use case in my opinion. Am I missing something? Is there another way to condition on some data and find a posterior (having latents are a mix of Categorical and Bernoulli variables) using importance sampling? 

I understand that I can use variational inference but I want to make it more precise by using importance sampling in the end (as it was suggested in the tutorials). This seems like a valid use case of importance sampling. If pyro is planning to support importance sampling anyway, this needs to be fixed.

**Comment by fehiepsi** [comment] 2018-11-28 20:03
@gursimar If you want, you can do this way
```
...
posterior = pyro.infer.Importance(weather, num_samples = 100)
sample_idx = posterior._categorical.sample().item()
sampled_trace = posterior.exec_traces[sample_idx]
```
Or you can modify the MarginalEmpirical class to something like
```
class CustomEmpiricalMarginal(object):
    def __init__(self, trace_posterior, sites=None):
        self._samples = OrderedDict({})
        self._populate_traces(trace_posterior, sites)
        self._categorical = Categorical(logits=trace_posterior.log_weights)

    def _populate_traces(self, trace_posterior, sites):
        samples_buffer = defaultdict(list)
        for trace in trace_posterior.exec_traces:
            for site in sites:
                 samples_buffer[site].append(trace.nodes[site]["value"])
        for site in sites:
            self._samples[site] = torch.stack(samples_buffer)

    def sample(self, sample_shape=torch.Size([])):
        idxs = self._categorical.sample(sample_shape=sample_shape)
        return OrderedDict([(site, self._samples[site][idxs]) for site in self._samples])
```

**Comment by fehiepsi** [comment] 2018-12-08 00:41
By #1649, we can call `.marginal().support()` on a posterior to get support of each latent site. Given that we have exposed `.log_weights` in TracePosterior, we are able to obtain this by using 3 lines of code
```
support = posterior.marginal().support()
sample_idx = dist.Categorical(posterior.log_weights).sample(sample_shape)
samples = {site: support[site][sample_idx] for site in support}
```
Given that mixed types are not suitable for Empirical distribution, I'll close this because this is not an issue.

**Closed by fehiepsi** 2018-12-08 00:41 UTC
Labels: enhancement, low priority
