### ISSUE TITLE
Can't use L-BFGS  due to the closure argument

### ISSUE THREAD

**Issue by MrHuff** [uber/pyro#1674] opened 2018-12-17 22:37 UTC
### Issue Description
When doing:

optim = pyro.optim.PyroOptim(torch.optim.LBFGS,{})
svi = SVI(model, guide, optim, loss=Trace_ELBO(), num_samples=1000)

for some model and guide I specified according to the Bayesian Regression I can't run svi.step(...). 

### Environment
 - OS and python version: Fedora 29, 3.6.7
 - PyTorch version: 1.0 (stable release)
 - Pyro version: 0.3.0

### Code Snippet

When running the code (i.e. svi.step(...)) I get the following error:

Traceback (most recent call last):
  File "C:/Users/Robert/Documents/phd_projects/retail_asq_allo/test.py", line 91, in <module>
    loss = svi.step((rows,cols), ratings)
  File "C:\Users\Robert\Miniconda3\envs\allo_env\lib\site-packages\pyro\infer\svi.py", line 106, in step
    self.optim(params)
  File "C:\Users\Robert\Miniconda3\envs\allo_env\lib\site-packages\pyro\optim\optim.py", line 58, in __call__
    self.optim_objs[p].step(*args, **kwargs)
TypeError: step() missing 1 required positional argument: 'closure'

Process finished with exit code 1

My hypothesis is that it's the L-BFGS that makes things tricky with the closure argument:

        # torch.optim objects gets instantiated for any params that haven't been seen yet
        self.optim(params)

I would greatly appreciate any help on this or any advice on how to proceed.

Thank you!

Best regards,
Robert

**Comment by fehiepsi** [comment] 2018-12-17 22:43
For an example of using LBFGS, you can take a look at [this method](https://github.com/fehiepsi/rethinking-pyro/blob/master/notebooks/rethinking.py#L54). Please take a look at [Custom SVI Objectives](http://pyro.ai/examples/custom_objectives.html#A-Lower-Level-Pattern) tutorial for better understanding.

**Comment by MrHuff** [comment] 2018-12-17 23:08
Thanks a lot @fehiepsi

**Comment by eb8680** [comment] 2018-12-17 23:15
Closing as duplicate of #1519

**Closed by eb8680** 2018-12-17 23:15 UTC
