### ISSUE TITLE
Some tests fail under pytorch 0.3

### ISSUE THREAD

**Issue by zou3519** [uber/pyro#554] opened 2017-11-10 14:41 UTC
Hi, 
The folks over at [pytorch](https://github.com/pytorch/pytorch) are working on cutting a new 0.3 release. We'd like to make the transition as smooth as possible so we're testing various community repos that use pytorch with the release.

I built pyro from source and ran the tests with `make test`, replacing `test` with a number of the targets in the Makefile, and at least three are failing right now. Since make exits if any of the tests fail, more than two could be failing.

The outputs of these tests are listed in the gist below. These failures could be problems with pytorch / I also might not be running them correctly, so I'm looking into them as well.

https://gist.github.com/zou3519/e9cc880defd9741d0317c2ab9204661d

cc @soumith

**Comment by fritzo** [comment] 2017-11-10 16:50
Thanks, @zou3519 ! I'm looking into this now by testing PyTorch's `v0.3.0` branch + Pyro `0.1.1` tag.

**Comment by fritzo** [comment] 2017-11-10 20:45
@zou3519 I'm still diagnosing a failure of `test_subsample_gradient` that you found. To reproduce:
```sh
pytest -v tests/infer/test_gradient.py::test_subsample_gradient
```

**Comment by fritzo** [comment] 2017-11-10 22:30
It looks like the only issues with PyTorch v0.3.0 are slight changes to randomness that cause some of Pyro's flaky tests to fail.

BTW I noticed PyTorch v0.3.0 is about 2x faster than v0.2.0 on some tests. Great work!

**Comment by fritzo** [comment] 2017-11-14 22:22
Tests still pass on PyTorch v0.3.0 f20fb2c + Pyro 0.1.2 daa7476.

**Comment by martinjankowiak** [comment] 2017-12-17 20:38
@fritzo can we close this?

**Comment by fritzo** [comment] 2017-12-18 05:19
Yes, we fixed all tests.

**Closed by fritzo** 2017-12-18 05:19 UTC
Labels: high priority, testing
