### ISSUE TITLE
Sample from Categorical returning wrong shape

### ISSUE THREAD

**Issue by kgero** [uber/pyro#1647] opened 2018-12-07 03:04 UTC
### Issue Description
When sampling from a Categorical, my model continually makes a larger and larger tensor -- even though, as I understand it, it should always be returning an integer. I can't recreate this in the terminal, unfortunately, but here is my model:

```py
@config_enumerate(default='parallel')
@poutine.broadcast
def model(data):
    beta = pyro.sample('beta', dist.Dirichlet(torch.ones(K, V), validate_args=False).independent(1))
    print('beta.shape', beta.shape)
    for t in pyro.irange('timeslice', T):
        if t == 0:
            theta = pyro.sample('theta_t{}'.format(t), dist.Normal(torch.ones(K), SCALE).independent(1))
        else:
            theta = pyro.sample('theta_t{}'.format(t), dist.Normal(theta_prev, SCALE).independent(1))
        theta = torch.tensor([max(i, 0.001) for i in theta])
        theta = theta / sum(theta)
        print('theta.shape', theta.shape)
        for d in pyro.irange('docs_t{}'.format(t), N[t]):
            z = pyro.sample('z_t{}_d{}'.format(t, d), dist.Categorical(theta))
            print('z.shape', z.shape)
            with pyro.iarange('words_t{}_d{}'.format(t, d), L[t][d]):
                pyro.sample('w_t{}_d{}'.format(t, d), dist.Categorical(beta[z,:]), obs=data[t][d])
        theta_prev = theta
```
And here is a sample output showing the shape of `z` getting larger and larger:

```
beta.shape torch.Size([2, 14])
theta.shape torch.Size([2])
z.shape torch.Size([2, 1])
z.shape torch.Size([2, 1, 1])
z.shape torch.Size([2, 1, 1, 1])
theta.shape torch.Size([2])
z.shape torch.Size([2, 1, 1, 1, 1])
z.shape torch.Size([2, 1, 1, 1, 1, 1])
z.shape torch.Size([2, 1, 1, 1, 1, 1, 1])
theta.shape torch.Size([2])
z.shape torch.Size([2, 1, 1, 1, 1, 1, 1, 1])
z.shape torch.Size([2, 1, 1, 1, 1, 1, 1, 1, 1])
z.shape torch.Size([2, 1, 1, 1, 1, 1, 1, 1, 1, 1])
```

### Environment
Mac OS, Python 3.6.5
torch.__version__ 1.0.0.dev20181206
pyro.__version__ 0.2.1+9e76df6c

**Comment by fritzo** [comment] 2018-12-07 03:10
That's actually the intended behavior of enumeration. What's happening is that Pyro allocates new dimension for enumeration, implicitly creating an enormous many-dimensional tensor, but via cheap-to-reason-about factors. Take a look at the [tensor shapes tutorial](https://github.com/uber/pyro/blob/dev/tutorial/source/tensor_shapes.ipynb) and [enumeration tutorial](https://github.com/uber/pyro/blob/dev/tutorial/source/enumeration.ipynb).

If you have a more than 64 time steps (or more than 25 on GPU), you could try using `pyro.markov` instead of `pyro.irange`, so that tensor dimensions can be reused across steps.

**Comment by fritzo** [comment] 2018-12-07 04:16
Closing since this is actually not a bug. Feel free to continue discussion here on or forum.pyro.ai.

**Closed by fritzo** 2018-12-07 04:16 UTC
